exclude_node_title.settings:
  type: config_object
  label: 'Exclude Node Title settings'
  mapping:
    exclude_node_title_nid_list:
      type: sequence
      label: 'Nodes with excluded titles'
      sequence:
        type: integer
        label: 'Node ID'
    exclude_node_title_translation_sync:
      type: boolean
      label: 'Translation sync (deprecated)'
    exclude_node_title_search:
      type: boolean
      label: 'Exclude title from search results'
    exclude_node_title_content_type_value:
      type: sequence
      label: 'Exclude type'
      sequence:
        type: string
        label: 'Machine name of exclude type'
    exclude_node_title_content_type_modes:
      type: sequence
      label: 'View modes with Exclude Node Title enabled'
      sequence:
        type: sequence
        label: 'Node type'
        sequence:
          type: string
          label: 'View mode'

